### ISSUE TITLE
Matlab Parity with Python 

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-MATLAB#110]
https://github.com/MHKiT-Software/MHKiT-Python/pull/130 - WDRT (Chris)
https://github.com/MHKiT-Software/MHKiT-Python/pull/132 - Delft3D (Andrew)
https://github.com/MHKiT-Software/MHKiT-Python/pull/141 - WDRT(Chris)
https://github.com/MHKiT-Software/MHKiT-Python/pull/152 - NDBC Metocean
https://github.com/MHKiT-Software/MHKiT-Python/pull/168 - Delf3D (Andrew)
https://github.com/MHKiT-Software/MHKiT-Python/pull/187 - metocean module (Chris)
https://github.com/MHKiT-Software/MHKiT-Python/pull/193 - loads module (Chris)
https://github.com/MHKiT-Software/MHKiT-Python/pull/197 - Directional NDBC
https://github.com/MHKiT-Software/MHKiT-Python/pull/199 - Delft3d example notebook (Andrew)
https://github.com/MHKiT-Software/MHKiT-Python/pull/205 - graphics bug fix
https://github.com/MHKiT-Software/MHKiT-Python/pull/210 - wave resource update 
https://github.com/MHKiT-Software/MHKiT-Python/pull/212 - DOLfYN updates (Andrew)
https://github.com/MHKiT-Software/MHKiT-Python/pull/220 - WPTO hindcast (Chris)
https://github.com/MHKiT-Software/MHKiT-Python/pull/232) - DOLfYN (Andrew)
https://github.com/MHKiT-Software/MHKiT-Python/pull/235 - Mooring (Chris)
https://github.com/MHKiT-Software/MHKiT-Python/pull/236 - Tidal Power Performance (Andrew)
https://github.com/MHKiT-Software/MHKiT-Python/pull/239 - NDBC station metadata
https://github.com/MHKiT-Software/MHKiT-Python/pull/248 - Delft3D (Andrew)
https://github.com/MHKiT-Software/MHKiT-Python/pull/250 - surface elevation 
https://github.com/MHKiT-Software/MHKiT-Python/pull/252 - uncrossing analysis 
https://github.com/MHKiT-Software/MHKiT-Python/pull/271 - Delft3D (Andrew)
https://github.com/MHKiT-Software/MHKiT-Python/pull/280 - DOLfYN (Andrew)

**Comment by simmsa** [comment]
# Detailed Progress Tracker

# River Module

## IO/Delft3D [Released - MHKiT-MATLAB v0.5.0]

- [x] [MHKiT-Python #132 Delft3D](https://github.com/MHKiT-Software/MHKiT-Python/pull/132) @simmsa #124
- [x] [MHKiT-Python #168 Delft3D](https://github.com/MHKiT-Software/MHKiT-Python/pull/168) @simmsa #124
- [x] [MHKiT-Python #199 Delft3D Example Notebook](https://github.com/MHKiT-Software/MHKiT-Python/pull/199) @simmsa #124
- [x] [MHKiT-Python #248 Delft3D](https://github.com/MHKiT-Software/MHKiT-Python/pull/248) @simmsa #124
- [x] [MHKiT-Python #271 Delft3D](https://github.com/MHKiT-Software/MHKiT-Python/pull/271) @simmsa #124

# Tidal Module

## Performance

- [ ] [MHKiT-Python #236 Tidal Power Performance](https://github.com/MHKiT-Software/MHKiT-Python/pull/236) @simmsa - Planned for MHKiT-MATLAB v0.7.0

# Utils Module

## Upcrossing Analysis [Complete]

- [x] [MHKiT-Python #252 Uncrossing Analysis](https://github.com/MHKiT-Software/MHKiT-Python/pull/252) @MShabara #151 - Planned For Release in MHKiT-MATLAB v0.6.0

# Strain Example

- [x] [MHKiT-Python #358 Strain Processing Example](https://github.com/MHKiT-Software/MHKiT-Python/pull/358) @simmsa #156 - Planned For Release in MHKiT-MATLAB v0.6.0

# DOLfYN Module

- [ ] Add Partial ACDP and Full ADV Example - @simmsa #141 - Planned for MHKiT-MATLAB v0.6.0
- [ ] Add Complete ADCP Example - @simmsa - Planned for MHKiT-MATLAB v0.7.0
- [ ] [MHKiT-Python #212 DOLfYN Updates](https://github.com/MHKiT-Software/MHKiT-Python/pull/212) @simmsa - Planned for MHKiT-MATLAB v0.7.0
- [ ] [MHKiT-Python #232 DOLfYN](https://github.com/MHKiT-Software/MHKiT-Python/pull/232) @simmsa - Planned for MHKiT-MATLAB v0.8.0
- [ ] [MHKiT-Python #280 DOLfYN](https://github.com/MHKiT-Software/MHKiT-Python/pull/280) @simmsa - Planned for MHKiT-MATLAB v0.8.0

# Wave Module

## Resource

- [x] [MHKiT-Python #250 Surface Elevation](https://github.com/MHKiT-Software/MHKiT-Python/pull/250) @simmsa [MHKiT-Python https://github.com/MHKiT-Software/MHKiT-Python/pull/341] - MHKiT-MATLAB v0.5.0
- [ ] [MHKiT-Python #210 Wave Resource Update](https://github.com/MHKiT-Software/MHKiT-Python/pull/210) <unassigned>

# WDRT

- [ ] [MHKiT-Python #141 WDRT](https://github.com/MHKiT-Software/MHKiT-Python/pull/141) @hivanov-nrel
- [ ] [MHKiT-Python #130 WDRT](https://github.com/MHKiT-Software/MHKiT-Python/pull/130) @hivanov-nrel

Need to Check Progress, Relevant PR's: PR #127, PR #147

## Metocean

- [ ] [MHKiT-Python #187 Metocean Module](https://github.com/MHKiT-Software/MHKiT-Python/pull/187) @hivanov-nrel

## I/O

### NDBC

- [ ] [MHKiT-Python #239 NDBC Station Metadata](https://github.com/MHKiT-Software/MHKiT-Python/pull/239) @MShabara
- [ ] [MHKiT-Python #197 Directional NDBC](https://github.com/MHKiT-Software/MHKiT-Python/pull/197) <unassigned>
- [ ] [MHKiT-Python #152 NDBC Metocean](https://github.com/MHKiT-Software/MHKiT-Python/pull/152) <unassigned>

### WPTO Hindcast

- [ ] [MHKiT-Python #220 WPTO Hindcast](https://github.com/MHKiT-Software/MHKiT-Python/pull/220) @hivanov-nrel

# Loads Module

- [ ] [MHKiT-Python #193 Loads Module](https://github.com/MHKiT-Software/MHKiT-Python/pull/193) @hivanov-nrel

# Mooring Module

- [ ] [MHKiT-Python #235 Mooring](https://github.com/MHKiT-Software/MHKiT-Python/pull/235) @hivanov-nrel PR #253 - Planned for MHKiT-MATLAB v0.7.0

# Acoustics Module

- [ ] [MHKiT-Python #349 Acoustics Module](https://github.com/MHKiT-Software/MHKiT-Python/pull/349) <unassigned>

# Misc

- [ ] [MHKiT-Python #205 Graphics Bug Fix](https://github.com/MHKiT-Software/MHKiT-Python/pull/205) <unassigned>
